use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use hnk_tools::NormalizedSpec;

use crate::rust::render_project_files;

#[derive(Debug, Clone)]
pub struct GenerateOptions {
    pub create_app_scaffold: bool,
    pub generated_header: String,
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            create_app_scaffold: true,
            generated_header:
                "// @generated by hnk-core. Manual edits in generated files will be overwritten."
                    .to_string(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GeneratedFileStatus {
    Created,
    Updated,
    Preserved,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerateReport {
    pub component_count: usize,
    pub generated_files: Vec<PathBuf>,
    pub created_files: Vec<PathBuf>,
    pub updated_files: Vec<PathBuf>,
    pub preserved_files: Vec<PathBuf>,
}

#[derive(Debug)]
pub enum GenerateError {
    Io { path: PathBuf, source: io::Error },
}

impl fmt::Display for GenerateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GenerateError::Io { path, source } => {
                write!(f, "I/O error while touching {}: {source}", path.display())
            }
        }
    }
}

impl std::error::Error for GenerateError {}

pub fn generate(
    spec: &NormalizedSpec,
    out_dir: &Path,
    opts: GenerateOptions,
) -> Result<GenerateReport, GenerateError> {
    ensure_dir(out_dir)?;

    let generated_root = out_dir.join("src/generated");
    let app_root = out_dir.join("src/app");
    ensure_dir(&generated_root)?;
    ensure_dir(&app_root)?;

    let rendered = render_project_files(spec, &opts.generated_header, opts.create_app_scaffold);

    let mut report = GenerateReport {
        component_count: spec.components.len(),
        generated_files: Vec::new(),
        created_files: Vec::new(),
        updated_files: Vec::new(),
        preserved_files: Vec::new(),
    };

    for file in rendered {
        let path = out_dir.join(&file.relative_path);
        let status = if file.preserve_existing {
            write_preserving_existing(&path, &file.contents)?
        } else {
            write_overwriting(&path, &file.contents)?
        };

        report.generated_files.push(path.clone());
        match status {
            GeneratedFileStatus::Created => report.created_files.push(path),
            GeneratedFileStatus::Updated => report.updated_files.push(path),
            GeneratedFileStatus::Preserved => report.preserved_files.push(path),
        }
    }

    Ok(report)
}

fn ensure_dir(path: &Path) -> Result<(), GenerateError> {
    fs::create_dir_all(path).map_err(|source| GenerateError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn write_overwriting(path: &Path, contents: &str) -> Result<GeneratedFileStatus, GenerateError> {
    if let Some(parent) = path.parent() {
        ensure_dir(parent)?;
    }

    let status = if path.exists() {
        GeneratedFileStatus::Updated
    } else {
        GeneratedFileStatus::Created
    };

    fs::write(path, contents).map_err(|source| GenerateError::Io {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(status)
}

fn write_preserving_existing(
    path: &Path,
    contents: &str,
) -> Result<GeneratedFileStatus, GenerateError> {
    if path.exists() {
        return Ok(GeneratedFileStatus::Preserved);
    }

    if let Some(parent) = path.parent() {
        ensure_dir(parent)?;
    }

    fs::write(path, contents).map_err(|source| GenerateError::Io {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(GeneratedFileStatus::Created)
}
